// Code generated by Molizen. DO NOT EDIT.

// Package actor_user is a generated Molizen package.
package actor_user

import (
	sync "sync"

	context "github.com/sanposhiho/molizen/context"
	future "github.com/sanposhiho/molizen/future"
)

// UserActor is a actor of User interface.
type UserActor struct {
	lock     sync.Mutex
	internal User
}

type User interface {
	SetAge(ctx context.Context, age int)
	GetAge(ctx context.Context) int
}

func New(internal User) *UserActor {
	return &UserActor{
		internal: internal,
	}
}

// GetAgeResult is the result type for GetAge.
type GetAgeResult struct {
	Ret0 int
}

// GetAge actor base method.
func (a *UserActor) GetAge(ctx context.Context) *future.Future[GetAgeResult] {
	newctx := ctx.NewChildContext(a, a.lock.Lock, a.lock.Unlock)

	f := future.New[GetAgeResult](ctx.SenderLocker(), ctx.SenderUnlocker())
	go func() {
		a.lock.Lock()
		defer a.lock.Unlock()

		ret0 := a.internal.GetAge(newctx)

		ret := GetAgeResult{
			Ret0: ret0,
		}

		f.Send(ret)
	}()

	return f
}

// SetAgeResult is the result type for SetAge.
type SetAgeResult struct {
}

// SetAge actor base method.
func (a *UserActor) SetAge(ctx context.Context, age int) *future.Future[SetAgeResult] {
	newctx := ctx.NewChildContext(a, a.lock.Lock, a.lock.Unlock)

	f := future.New[SetAgeResult](ctx.SenderLocker(), ctx.SenderUnlocker())
	go func() {
		a.lock.Lock()
		defer a.lock.Unlock()

		a.internal.SetAge(newctx, age)

		ret := SetAgeResult{}

		f.Send(ret)
	}()

	return f
}
